networks:
  backend:

volumes:
  pgdata:
  appdata:
  csvdata:

services:
  db:
    image: postgres:16
    container_name: iss_db
    environment:
      POSTGRES_DB: monolith
      POSTGRES_USER: monouser
      POSTGRES_PASSWORD: monopass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monouser -d monolith"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - backend
    ports:
      - "5432:5432"

  rust_iss:
    build:
      context: ./services/rust-iss
    container_name: rust_iss
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://monouser:monopass@db:5432/monolith}
      NASA_API_URL: ${NASA_API_URL:-}
      NASA_API_KEY: ${NASA_API_KEY:-}
      FETCH_EVERY_SECONDS: ${FETCH_EVERY_SECONDS:-600}
      WHERE_ISS_URL: ${WHERE_ISS_URL:-https://api.wheretheiss.at/v1/satellites/25544}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8081:3000"

  react_client:
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile
    build: ./client
    container_name: react_client
    # ports:
    #   - "5173:5173"
    networks:
      - backend
  nginx:
    image: nginx:1.27-alpine
    container_name: web_nginx
    depends_on:
      rust_iss:
        condition: service_healthy
    volumes:
      - ./client/dist:/usr/share/nginx/html
      # - ./services/php-web/laravel-patches:/var/www/html
      - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./services/php-web/laravel-patches:/var/www/html:ro
      # - ./services/php-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "8080:80"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  visualizer:
    build:
      context: ./services/visualizer
    container_name: visualizer
    volumes:
      - ./csv_out:/app/csv_out
    ports:
      - "8501:8501"

  pascal_legacy:
    build:
      context: ./services/pascal-legacy
    container_name: pascal_legacy
    environment:
      CSV_OUT_DIR: /data/csv
      GEN_PERIOD_SEC: ${PAS_LEGACY_PERIOD:-300}
      PGHOST: db
      PGPORT: 5432
      PGUSER: monouser
      PGPASSWORD: monopass
      PGDATABASE: monolith
    depends_on:
      db:
        condition: service_healthy
    # volumes:
    #   - csvdata:/data/csv
    volumes:
      - ./csv_out:/data/csv
    networks:
      - backend
